# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: crawler.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'crawler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcrawler.proto\"\x19\n\nURLRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"-\n\x0cPageResponse\x12\x0e\n\x06titles\x18\x01 \x03(\t\x12\r\n\x05links\x18\x02 \x03(\t22\n\x07\x43rawler\x12\'\n\tFetchPage\x12\x0b.URLRequest\x1a\r.PageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crawler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_URLREQUEST']._serialized_start=17
  _globals['_URLREQUEST']._serialized_end=42
  _globals['_PAGERESPONSE']._serialized_start=44
  _globals['_PAGERESPONSE']._serialized_end=89
  _globals['_CRAWLER']._serialized_start=91
  _globals['_CRAWLER']._serialized_end=141
# @@protoc_insertion_point(module_scope)
